enabled=true
#url=seri.sailpointdemo.com:8080/identityiq
#username=spadmin
#password=admin
mode=IDN
#domain=companyXYZ-poc
domain=<your_tenant_name>
#idn_username=<your_admin_username>
#idn_password=<your_admin_password>
client_id=<your_pat_client_id>
client_secret=client_id=<your_pat_secret>
source_id=<the_source_id_you_want_to_aggregate>