/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const checkSodPendingOperationSchema = defineOperationSchema({
    hasViolations: 'boolean',
    identityId: 'string',
    violatedPolicyNames: 'string[]',
})
