#!/usr/bin/env node
/**
 * Generates per-operation *.schema.ts sidecars, auto-registry.ts, and syncs connector-spec.json.
 *
 * Discovery rules mirror scripts/templates/operation-introspection.ts:
 * - Auto ops: modules with `command` literal + exactly one customOperation export
 * - Manual ops: index.ts registrations where the handler module has no `command` literal
 */
import * as fs from 'fs'
import * as path from 'path'
import {
    AutoOperationDiscovery,
    discoverAllOperations,
    extractOperationSignature,
    hasOperationSignature,
} from './templates/operation-introspection'
import { OperationField } from './templates/types'

const BANNER = '/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */'

const PROJECT_ROOT = path.resolve(__dirname, '..')
const INDEX_PATH = path.join(PROJECT_ROOT, 'src/operations/index.ts')
const CONNECTOR_SPEC_PATH = path.join(PROJECT_ROOT, 'connector-spec.json')

function fieldToSpec(field: OperationField): string {
    if (field.optional) {
        return `{ type: '${field.type}', optional: true }`
    }
    return `'${field.type}'`
}

/** Renders a schema sidecar file for a registered operation handler. */
export function renderOperationSchemaSidecar(handlerName: string, outputFields: OperationField[]): string {
    const sorted = [...outputFields].sort((a, b) => a.name.localeCompare(b.name))
    const fieldLines = sorted.map((field) => `    ${field.name}: ${fieldToSpec(field)},`).join('\n')

    return `${BANNER}
import { defineOperationSchema } from '../framework'

export const ${handlerName}Schema = defineOperationSchema({
${fieldLines}
})
`
}

/** Renders src/operations/auto-registry.ts for auto-discovered command registration. */
export function renderAutoRegistry(autoOps: AutoOperationDiscovery[]): string {
    if (autoOps.length === 0) {
        return `${BANNER}
import { Connector } from '@sailpoint/connector-sdk'

export function registerAutoOperations(connector: Connector): Connector {
    return connector
}
`
    }

    const handlerImports = autoOps
        .map((operation) => {
            const moduleName = path.basename(operation.modulePath, '.ts')
            return `import { ${operation.handlerName} } from './${moduleName}'`
        })
        .join('\n')
    const schemaImports = autoOps
        .map((operation) => {
            const moduleName = path.basename(operation.modulePath, '.ts')
            return `import { ${operation.handlerName}Schema } from './${moduleName}.schema'`
        })
        .join('\n')
    const registrations = autoOps
        .map((operation) => `registerOperationSchema('${operation.command}', ${operation.handlerName}Schema)`)
        .join('\n')
    const commands = autoOps.map((operation) => `.command('${operation.command}', ${operation.handlerName})`).join('')

    return `${BANNER}
import { Connector } from '@sailpoint/connector-sdk'
import { registerOperationSchema } from '../framework'
${handlerImports}
${schemaImports}

${registrations}

export function registerAutoOperations(connector: Connector): Connector {
    return connector${commands}
}
`
}

/** Replaces connector-spec.json commands[] with discovered commands, preserving other keys. */
export function syncConnectorSpecCommands(commands: string[], specPath: string): void {
    const spec = JSON.parse(fs.readFileSync(specPath, 'utf-8'))
    spec.commands = [...commands].sort()
    fs.writeFileSync(specPath, `${JSON.stringify(spec, null, '\t')}\n`)
}

function sidecarPathForModule(modulePath: string): string {
    const dir = path.dirname(modulePath)
    const basename = path.basename(modulePath, '.ts')
    return path.join(dir, `${basename}.schema.ts`)
}

export function generateOperationSchemas(options?: {
    indexPath?: string
    operationsDir?: string
    specPath?: string
}): void {
    const indexPath = options?.indexPath ?? INDEX_PATH
    const operationsDir = options?.operationsDir ?? path.dirname(indexPath)
    const specPath = options?.specPath ?? CONNECTOR_SPEC_PATH

    const discoveries = discoverAllOperations(operationsDir, indexPath)
    const autoOps = discoveries.filter((operation) => operation.source === 'auto')

    if (discoveries.length === 0) {
        console.warn('[codegen:schemas] No operations found')
    }

    for (const discovery of discoveries) {
        const { modulePath, handlerName, command } = discovery

        if (!fs.existsSync(modulePath)) {
            throw new Error(`[codegen:schemas] Handler module not found: ${modulePath} (${command})`)
        }

        if (!hasOperationSignature(modulePath)) {
            throw new Error(
                `[codegen:schemas] No OperationSignature interface found in ${modulePath} (${command}, handler ${handlerName})`
            )
        }

        const { output } = extractOperationSignature(modulePath)
        if (output.length === 0) {
            console.warn(`[codegen:schemas] No output fields in ${modulePath} (${command})`)
        }

        const sidecarPath = sidecarPathForModule(modulePath)
        const content = renderOperationSchemaSidecar(handlerName, output)
        fs.writeFileSync(sidecarPath, content)
        console.log(`[codegen:schemas] Wrote ${path.relative(PROJECT_ROOT, sidecarPath)}`)
    }

    const autoRegistryPath = path.join(operationsDir, 'auto-registry.ts')
    fs.writeFileSync(autoRegistryPath, renderAutoRegistry(autoOps))
    console.log(`[codegen:schemas] Wrote ${path.relative(PROJECT_ROOT, autoRegistryPath)}`)

    syncConnectorSpecCommands(
        discoveries.map((operation) => operation.command),
        specPath
    )
    console.log(`[codegen:schemas] Synced ${path.relative(PROJECT_ROOT, specPath)} commands[]`)
}

if (require.main === module) {
    try {
        generateOperationSchemas()
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        console.error(message)
        process.exit(1)
    }
}
