import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
import { afterEach, describe, expect, it } from 'vitest'
import {
    extractOperationSignature,
    loadOperationMeta,
} from './templates/operation-introspection'
import { generateOperationSchemas, renderOperationSchemaSidecar } from './generate-operation-schemas'

describe('renderOperationSchemaSidecar', () => {
    it('emits banner, import, and alphabetically sorted fields', () => {
        const content = renderOperationSchemaSidecar('exampleOperation', [
            { name: 'summary', optional: false, type: 'string' },
            { name: 'step', optional: true, type: 'string' },
        ])

        expect(content).toContain('AUTO-GENERATED by npm run codegen:schemas')
        expect(content).toContain("import { defineOperationSchema } from '../framework'")
        expect(content).toContain('export const exampleOperationSchema = defineOperationSchema({')
        expect(content).toContain("summary: 'string',")
        expect(content).toContain("step: { type: 'string', optional: true },")

        const stepIndex = content.indexOf('step:')
        const summaryIndex = content.indexOf('summary:')
        expect(stepIndex).toBeLessThan(summaryIndex)
    })
})

describe('generateOperationSchemas', () => {
    let tempDir: string

    afterEach(() => {
        if (tempDir && fs.existsSync(tempDir)) {
            fs.rmSync(tempDir, { recursive: true, force: true })
        }
    })

    it('writes example-operation.schema.ts with fields matching introspection', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-codegen-'))
        const operationsDir = path.join(tempDir, 'operations')
        fs.mkdirSync(operationsDir, { recursive: true })

        fs.writeFileSync(
            path.join(operationsDir, 'example-operation.ts'),
            `import { OperationSignature } from '../framework'

export interface ExampleOperation extends OperationSignature {
    input: { message?: string }
    output: {
        summary: string
        step?: string
    }
}

export const exampleOperation = async () => {}
`
        )

        fs.writeFileSync(
            path.join(operationsDir, 'index.ts'),
            `import { exampleOperation } from './example-operation'

export function registerCommands(connector: unknown) {
    return connector.command('custom:example', exampleOperation)
}
`
        )

        generateOperationSchemas({ indexPath: path.join(operationsDir, 'index.ts') })

        const sidecarPath = path.join(operationsDir, 'example-operation.schema.ts')
        expect(fs.existsSync(sidecarPath)).toBe(true)

        const sidecar = fs.readFileSync(sidecarPath, 'utf-8')
        expect(sidecar).toContain('export const exampleOperationSchema = defineOperationSchema({')
        expect(sidecar).toContain("summary: 'string',")
        expect(sidecar).toContain("step: { type: 'string', optional: true },")

        const { output } = extractOperationSignature(path.join(operationsDir, 'example-operation.ts'))
        expect(output.map((field) => field.name).sort()).toEqual(['step', 'summary'])
    })

    it('throws when handler module lacks OperationSignature', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-codegen-'))
        const operationsDir = path.join(tempDir, 'operations')
        fs.mkdirSync(operationsDir, { recursive: true })

        fs.writeFileSync(
            path.join(operationsDir, 'broken-operation.ts'),
            `export const brokenOperation = async () => {}
`
        )

        fs.writeFileSync(
            path.join(operationsDir, 'index.ts'),
            `import { brokenOperation } from './broken-operation'

export function registerCommands(connector: unknown) {
    return connector.command('custom:broken', brokenOperation)
}
`
        )

        expect(() => generateOperationSchemas({ indexPath: path.join(operationsDir, 'index.ts') })).toThrow(
            /No OperationSignature interface found in .*broken-operation\.ts/
        )
    })

    it('matches templates generator output fields for the real example operation', () => {
        const projectRoot = path.resolve(__dirname, '..')
        const indexPath = path.join(projectRoot, 'src/operations/index.ts')
        const examplePath = path.join(projectRoot, 'src/operations/example-operation.ts')

        const meta = loadOperationMeta(indexPath).find((operation) => operation.command === 'custom:example')
        const { output } = extractOperationSignature(examplePath)

        expect(meta?.output).toEqual(output)
    })
})
