import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
import { afterEach, describe, expect, it } from 'vitest'
import {
    extractOperationSignature,
    loadOperationMeta,
} from './templates/operation-introspection'
import {
    generateOperationSchemas,
    renderAutoRegistry,
    renderOperationSchemaSidecar,
    syncConnectorSpecCommands,
} from './generate-operation-schemas'

describe('renderOperationSchemaSidecar', () => {
    it('emits banner, import, and alphabetically sorted fields', () => {
        const content = renderOperationSchemaSidecar('exampleOperation', [
            { name: 'summary', optional: false, type: 'string' },
            { name: 'step', optional: true, type: 'string' },
        ])

        expect(content).toContain('AUTO-GENERATED by npm run codegen:schemas')
        expect(content).toContain("import { defineOperationSchema } from '../framework'")
        expect(content).toContain('export const exampleOperationSchema = defineOperationSchema({')
        expect(content).toContain("summary: 'string',")
        expect(content).toContain("step: { type: 'string', optional: true },")

        const stepIndex = content.indexOf('step:')
        const summaryIndex = content.indexOf('summary:')
        expect(stepIndex).toBeLessThan(summaryIndex)
    })
})

describe('renderAutoRegistry', () => {
    it('emits registerAutoOperations with schema registration for auto ops', () => {
        const content = renderAutoRegistry([
            {
                command: 'custom:example',
                handlerName: 'exampleOperation',
                modulePath: '/tmp/example-operation.ts',
            },
        ])

        expect(content).toContain("registerOperationSchema('custom:example', exampleOperationSchema)")
        expect(content).toContain(".command('custom:example', exampleOperation)")
        expect(content).toContain("import { exampleOperation } from './example-operation'")
    })

    it('emits a no-op registerAutoOperations when there are no auto ops', () => {
        const content = renderAutoRegistry([])
        expect(content).toContain('export function registerAutoOperations(connector: Connector): Connector {')
        expect(content).toContain('return connector')
        expect(content).not.toContain('registerOperationSchema')
    })
})

describe('syncConnectorSpecCommands', () => {
    let tempDir: string

    afterEach(() => {
        if (tempDir && fs.existsSync(tempDir)) {
            fs.rmSync(tempDir, { recursive: true, force: true })
        }
    })

    it('replaces commands[] while preserving other manifest keys', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-sync-'))
        const specPath = path.join(tempDir, 'connector-spec.json')
        fs.writeFileSync(
            specPath,
            `${JSON.stringify({ name: 'test-connector', commands: ['custom:old'], sourceConfig: [{ key: 'token' }] }, null, '\t')}\n`
        )

        syncConnectorSpecCommands(['custom:example', 'custom:manual'], specPath)

        const spec = JSON.parse(fs.readFileSync(specPath, 'utf-8'))
        expect(spec.commands).toEqual(['custom:example', 'custom:manual'])
        expect(spec.name).toBe('test-connector')
        expect(spec.sourceConfig).toEqual([{ key: 'token' }])
    })
})

describe('generateOperationSchemas', () => {
    let tempDir: string

    afterEach(() => {
        if (tempDir && fs.existsSync(tempDir)) {
            fs.rmSync(tempDir, { recursive: true, force: true })
        }
    })

    it('writes example-operation.schema.ts with fields matching introspection', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-codegen-'))
        const operationsDir = path.join(tempDir, 'operations')
        fs.mkdirSync(operationsDir, { recursive: true })

        fs.writeFileSync(
            path.join(operationsDir, 'example-operation.ts'),
            `import { customOperation, OperationSignature } from '../framework'

export interface ExampleOperation extends OperationSignature {
    command: 'custom:example'
    input: { message?: string }
    output: {
        summary: string
        step?: string
    }
}

export const exampleOperation = customOperation<ExampleOperation>(async () => {})
`
        )

        fs.writeFileSync(
            path.join(operationsDir, 'index.ts'),
            `import { Connector } from '@sailpoint/connector-sdk'
import { registerAutoOperations } from './auto-registry'

export function registerCommands(connector: Connector): Connector {
    return registerAutoOperations(connector)
}
`
        )

        const specPath = path.join(tempDir, 'connector-spec.json')
        fs.writeFileSync(specPath, `${JSON.stringify({ name: 'test', commands: [], sourceConfig: [] }, null, '\t')}\n`)

        generateOperationSchemas({
            indexPath: path.join(operationsDir, 'index.ts'),
            specPath,
        })

        const sidecarPath = path.join(operationsDir, 'example-operation.schema.ts')
        expect(fs.existsSync(sidecarPath)).toBe(true)

        const autoRegistryPath = path.join(operationsDir, 'auto-registry.ts')
        expect(fs.existsSync(autoRegistryPath)).toBe(true)
        const autoRegistry = fs.readFileSync(autoRegistryPath, 'utf-8')
        expect(autoRegistry).toContain("registerOperationSchema('custom:example', exampleOperationSchema)")

        const spec = JSON.parse(fs.readFileSync(specPath, 'utf-8'))
        expect(spec.commands).toEqual(['custom:example'])

        const sidecar = fs.readFileSync(sidecarPath, 'utf-8')
        expect(sidecar).toContain('export const exampleOperationSchema = defineOperationSchema({')
        expect(sidecar).toContain("summary: 'string',")
        expect(sidecar).toContain("step: { type: 'string', optional: true },")

        const { output } = extractOperationSignature(path.join(operationsDir, 'example-operation.ts'))
        expect(output.map((field) => field.name).sort()).toEqual(['step', 'summary'])
    })

    it('throws when auto-discovered and manual registrations collide', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-codegen-'))
        const operationsDir = path.join(tempDir, 'operations')
        fs.mkdirSync(operationsDir, { recursive: true })

        fs.writeFileSync(
            path.join(operationsDir, 'example-operation.ts'),
            `import { customOperation, OperationSignature } from '../framework'

export interface ExampleOperation extends OperationSignature {
    command: 'custom:example'
    input: {}
    output: { summary: string }
}

export const exampleOperation = customOperation<ExampleOperation>(async () => {})
`
        )

        fs.writeFileSync(
            path.join(operationsDir, 'index.ts'),
            `import { exampleOperation } from './example-operation'

export function registerCommands(connector: unknown) {
    return connector.command('custom:example', exampleOperation)
}
`
        )

        expect(() => generateOperationSchemas({ indexPath: path.join(operationsDir, 'index.ts') })).toThrow(
            /both auto-discovered and manually registered/
        )
    })

    it('throws when handler module lacks OperationSignature', () => {
        tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-codegen-'))
        const operationsDir = path.join(tempDir, 'operations')
        fs.mkdirSync(operationsDir, { recursive: true })

        fs.writeFileSync(
            path.join(operationsDir, 'broken-operation.ts'),
            `export const brokenOperation = async () => {}
`
        )

        fs.writeFileSync(
            path.join(operationsDir, 'index.ts'),
            `import { brokenOperation } from './broken-operation'

export function registerCommands(connector: unknown) {
    return connector.command('custom:broken', brokenOperation)
}
`
        )

        expect(() => generateOperationSchemas({ indexPath: path.join(operationsDir, 'index.ts') })).toThrow(
            /No OperationSignature interface found in .*broken-operation\.ts/
        )
    })

    it('matches templates generator output fields for the real example operation', () => {
        const projectRoot = path.resolve(__dirname, '..')
        const indexPath = path.join(projectRoot, 'src/operations/index.ts')
        const examplePath = path.join(projectRoot, 'src/operations/example-operation.ts')

        const meta = loadOperationMeta(indexPath).find((operation) => operation.command === 'custom:example')
        const { output } = extractOperationSignature(examplePath)

        expect(meta?.output).toEqual(output)
    })
})

