#!/usr/bin/env node
/**
 * Generates per-operation *.schema.ts sidecars from OperationSignature.output type literals.
 *
 * Discovery rules mirror scripts/templates/operation-introspection.ts:
 * - Parses src/operations/index.ts for custom:* command registrations
 * - Extracts output fields from each handler's OperationSignature interface
 */
import * as fs from 'fs'
import * as path from 'path'
import {
    extractOperationSignature,
    hasOperationSignature,
    parseRegistrations,
} from './templates/operation-introspection'
import { OperationField } from './templates/types'

const BANNER = '/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */'

const PROJECT_ROOT = path.resolve(__dirname, '..')
const INDEX_PATH = path.join(PROJECT_ROOT, 'src/operations/index.ts')

function fieldToSpec(field: OperationField): string {
    if (field.optional) {
        return `{ type: '${field.type}', optional: true }`
    }
    return `'${field.type}'`
}

/** Renders a schema sidecar file for a registered operation handler. */
export function renderOperationSchemaSidecar(handlerName: string, outputFields: OperationField[]): string {
    const sorted = [...outputFields].sort((a, b) => a.name.localeCompare(b.name))
    const fieldLines = sorted.map((field) => `    ${field.name}: ${fieldToSpec(field)},`).join('\n')

    return `${BANNER}
import { defineOperationSchema } from '../framework'

export const ${handlerName}Schema = defineOperationSchema({
${fieldLines}
})
`
}

function sidecarPathForModule(modulePath: string): string {
    const dir = path.dirname(modulePath)
    const basename = path.basename(modulePath, '.ts')
    return path.join(dir, `${basename}.schema.ts`)
}

export function generateOperationSchemas(options?: { indexPath?: string }): void {
    const indexPath = options?.indexPath ?? INDEX_PATH
    const registrations = parseRegistrations(indexPath)

    if (registrations.length === 0) {
        console.warn('[codegen:schemas] No registered operations found')
        return
    }

    for (const registration of registrations) {
        const { modulePath, handlerName, command } = registration

        if (!fs.existsSync(modulePath)) {
            throw new Error(`[codegen:schemas] Handler module not found: ${modulePath} (${command})`)
        }

        if (!hasOperationSignature(modulePath)) {
            throw new Error(
                `[codegen:schemas] No OperationSignature interface found in ${modulePath} (${command}, handler ${handlerName})`
            )
        }

        const { output } = extractOperationSignature(modulePath)
        if (output.length === 0) {
            console.warn(`[codegen:schemas] No output fields in ${modulePath} (${command})`)
        }

        const sidecarPath = sidecarPathForModule(modulePath)
        const content = renderOperationSchemaSidecar(handlerName, output)
        fs.writeFileSync(sidecarPath, content)
        console.log(`[codegen:schemas] Wrote ${path.relative(PROJECT_ROOT, sidecarPath)}`)
    }
}

if (require.main === module) {
    try {
        generateOperationSchemas()
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        console.error(message)
        process.exit(1)
    }
}
