/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const machineIdentityEntitlementsOperationSchema = defineOperationSchema({
    'machine-identity-entitlements:entitlements-added': 'number',
    'machine-identity-entitlements:failed-identity-ids': 'string[]',
    'machine-identity-entitlements:failure-details': 'string[]',
    'machine-identity-entitlements:identities-failed': 'number',
    'machine-identity-entitlements:identities-scanned': 'number',
    'machine-identity-entitlements:identities-skipped': 'number',
    'machine-identity-entitlements:identities-updated': 'number',
})
