/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const machineIdentityEntitlementsOperationSchema = defineOperationSchema({
    'machine-identity-entitlements:entitlement-ids': 'string[]',
    'machine-identity-entitlements:entitlement-source-ids': 'string[]',
    'machine-identity-entitlements:machine-identity-id': 'string',
})
