/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const accessModelSodRemediationOperationSchema = defineOperationSchema({
    'access-model-sod-remediation:form-email-body': { type: 'string', optional: true },
    'access-model-sod-remediation:form-email-header': { type: 'string', optional: true },
    'access-model-sod-remediation:form-email-recipients': { type: 'string[]', optional: true },
    'access-model-sod-remediation:form-url': { type: 'string', optional: true },
})
