/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const accessSodRemediationOperationSchema = defineOperationSchema({
    'access-sod-remediation:access-items-scanned': 'number',
    'access-sod-remediation:form-email-body': { type: 'string', optional: true },
    'access-sod-remediation:form-email-header': { type: 'string', optional: true },
    'access-sod-remediation:form-email-recipients': { type: 'string[]', optional: true },
    'access-sod-remediation:form-url': { type: 'string', optional: true },
    'access-sod-remediation:forms-persist-failed': { type: 'number', optional: true },
    'access-sod-remediation:forms-skipped': { type: 'number', optional: true },
    'access-sod-remediation:violations-found': 'number',
})
