/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const sodRemediationOperationSchema = defineOperationSchema({
    'sod-remediation:form-email-body': 'string',
    'sod-remediation:form-email-header': 'string',
    'sod-remediation:form-email-recipients': 'string[]',
    'sod-remediation:form-url': 'string',
})
