/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const sodRemediationOperationSchema = defineOperationSchema({
    'sod-remediation:form-url': 'string',
    'sod-remediation:owner-email': 'string',
    'sod-remediation:situation-header': 'string',
    'sod-remediation:situation-summary': 'string',
})
