/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const accessModelSodRemediationApplyOperationSchema = defineOperationSchema({
    'access-model-sod-remediation-apply:access-item-id': 'string',
    'access-model-sod-remediation-apply:access-item-type': 'string',
    'access-model-sod-remediation-apply:description-appended': { type: 'string', optional: true },
    'access-model-sod-remediation-apply:detached-access-profile-ids': { type: 'string[]', optional: true },
    'access-model-sod-remediation-apply:removed-entitlement-ids': { type: 'string[]', optional: true },
    'access-model-sod-remediation-apply:status': 'string',
})
