/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const evaluateAccessRequestRiskOperationSchema = defineOperationSchema({
    'evaluate-access-request-risk:contributing-ids': 'string',
    'evaluate-access-request-risk:situation-summary': 'string',
    'evaluate-access-request-risk:tier': 'string',
})
