/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const machineIdentityEntitlementsApplyOperationSchema = defineOperationSchema({
    'machine-identity-entitlements-apply:added-entitlement-ids': 'string[]',
    'machine-identity-entitlements-apply:machine-identity-id': 'string',
    'machine-identity-entitlements-apply:status': 'string',
})
