/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../framework'

export const accessRequestStatusOperationSchema = defineOperationSchema({
    accessOwnerId: { type: 'string', optional: true },
    bccEmails: { type: 'string[]', optional: true },
    emailBodyHtml: { type: 'string', optional: true },
    emailRoute: { type: 'string', optional: true },
    preApprovalComment: { type: 'string', optional: true },
})
