/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../framework'

export const accessRequestThresholdOperationSchema = defineOperationSchema({
    foundCount: 'number',
    grantedCount: 'number',
    pendingCount: 'number',
    requestedCount: 'number',
    sourceName: 'string',
    thresholdHit: 'boolean',
    thresholdValue: 'number',
})
