/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { Connector } from '@sailpoint/connector-sdk'
import { registerOperationSchema } from '../framework'
import { accessSodRemediationOperation } from './access-sod-remediation/index'
import { exampleOperation } from './example/index'
import { governanceGroupEmailsOperation } from './governance-group-emails/index'
import { preventiveSodCheckOperation } from './preventive-sod-check/index'
import { sodRemediationOperation } from './sod-remediation/index'
import { accessSodRemediationOperationSchema } from './access-sod-remediation/index.schema'
import { exampleOperationSchema } from './example/index.schema'
import { governanceGroupEmailsOperationSchema } from './governance-group-emails/index.schema'
import { preventiveSodCheckOperationSchema } from './preventive-sod-check/index.schema'
import { sodRemediationOperationSchema } from './sod-remediation/index.schema'

registerOperationSchema('custom:access-sod-remediation', accessSodRemediationOperationSchema)
registerOperationSchema('custom:example', exampleOperationSchema)
registerOperationSchema('custom:governance-group-emails', governanceGroupEmailsOperationSchema)
registerOperationSchema('custom:preventive-sod-check', preventiveSodCheckOperationSchema)
registerOperationSchema('custom:sod-remediation', sodRemediationOperationSchema)

export function registerAutoOperations(connector: Connector): Connector {
    return connector.command('custom:access-sod-remediation', accessSodRemediationOperation).command('custom:example', exampleOperation).command('custom:governance-group-emails', governanceGroupEmailsOperation).command('custom:preventive-sod-check', preventiveSodCheckOperation).command('custom:sod-remediation', sodRemediationOperation)
}
