/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { Connector } from '@sailpoint/connector-sdk'
import { registerOperationSchema } from '../framework'
import { exampleOperation } from './example-operation'
import { exampleOperationSchema } from './example-operation.schema'

registerOperationSchema('custom:example', exampleOperationSchema)

export function registerAutoOperations(connector: Connector): Connector {
    return connector.command('custom:example', exampleOperation)
}
