/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../framework'

export const govgroupEmailsOperationSchema = defineOperationSchema({
    emails: 'string[]',
})
