/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const accessExpirationRemindersOperationSchema = defineOperationSchema({
    'access-expiration-reminders:accessProfileId': { type: 'string', optional: true },
    'access-expiration-reminders:daysRemaining': { type: 'number', optional: true },
    'access-expiration-reminders:expirations-matched': 'number',
    'access-expiration-reminders:form-email-body': { type: 'string', optional: true },
    'access-expiration-reminders:form-email-header': { type: 'string', optional: true },
    'access-expiration-reminders:form-email-recipients': { type: 'string[]', optional: true },
    'access-expiration-reminders:form-url': { type: 'string', optional: true },
    'access-expiration-reminders:forms-created': 'number',
    'access-expiration-reminders:forms-launch-failed': { type: 'number', optional: true },
    'access-expiration-reminders:forms-overflow': { type: 'number', optional: true },
    'access-expiration-reminders:forms-persist-failed': { type: 'number', optional: true },
    'access-expiration-reminders:forms-skipped-existing': { type: 'number', optional: true },
    'access-expiration-reminders:forms-skipped-missing-manager-email': { type: 'number', optional: true },
    'access-expiration-reminders:identities-scanned': 'number',
    'access-expiration-reminders:identityId': { type: 'string', optional: true },
    'access-expiration-reminders:managerId': { type: 'string', optional: true },
    'access-expiration-reminders:removeDate': { type: 'string', optional: true },
})
