/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const accessExpirationRemindersOperationSchema = defineOperationSchema({
    'access-expiration-reminders:accessProfileId': { type: 'string', optional: true },
    'access-expiration-reminders:daysRemaining': { type: 'number', optional: true },
    'access-expiration-reminders:form-email-body': { type: 'string', optional: true },
    'access-expiration-reminders:form-email-header': { type: 'string', optional: true },
    'access-expiration-reminders:form-email-recipients': { type: 'string[]', optional: true },
    'access-expiration-reminders:form-url': { type: 'string', optional: true },
    'access-expiration-reminders:identityId': { type: 'string', optional: true },
    'access-expiration-reminders:managerId': { type: 'string', optional: true },
    'access-expiration-reminders:removeDate': { type: 'string', optional: true },
})
