/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const exampleOperationSchema = defineOperationSchema({
    step: { type: 'string', optional: true },
    summary: 'string',
})
