/** AUTO-GENERATED by npm run codegen:schemas — do not edit manually */
import { defineOperationSchema } from '../../framework'

export const preventiveSodCheckOperationSchema = defineOperationSchema({
    'preventive-sod-check:has-violation': 'boolean',
    'preventive-sod-check:situation-summary': 'string',
    'preventive-sod-check:violated-policy-names': 'string[]',
})
